# Generated by Django 4.0.3 on 2022-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NaverData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('contents', models.TextField()),
                ('keyword', models.CharField(max_length=50)),
                ('platform', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('reg_date', models.DateTimeField()),
                ('crawl_url', models.TextField()),
                ('view_cnt', models.IntegerField()),
                ('comment_cnt', models.IntegerField()),
            ],
            options={
                'db_table': 't_naver_data',
                'managed': True,
            },
        ),
    ]
