# Generated by Django 4.0.3 on 2022-03-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='naverdata',
            name='like_cnt',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
